"use client";

import { useEffect, useRef, useState } from "react";
import { ProgressBar } from "@/components/ui/ProgressBar";

function fmt(t: number) {
  if (!Number.isFinite(t)) return "0:00";
  const m = Math.floor(t / 60);
  const s = Math.floor(t % 60);
  return `${m}:${s.toString().padStart(2, "0")}`;
}

export function AudioPlayer({
  audioUrl,
  transcript,
  audioProvider,
}: {
  audioUrl: string;
  transcript: string;
  /** Deck pipeline only; omit for ad-hoc clips. */
  audioProvider?: "elevenlabs" | "gemini" | null;
}) {
  const ref = useRef<HTMLAudioElement | null>(null);
  const [playing, setPlaying] = useState(false);
  const [dur, setDur] = useState(0);
  const [cur, setCur] = useState(0);
  const [open, setOpen] = useState(false);
  const [seekPct, setSeekPct] = useState(0);

  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    const onMeta = () => setDur(el.duration || 0);
    const onTime = () => {
      setCur(el.currentTime || 0);
      if (el.duration) setSeekPct((el.currentTime / el.duration) * 100);
    };
    const onEnd = () => setPlaying(false);
    el.addEventListener("loadedmetadata", onMeta);
    el.addEventListener("timeupdate", onTime);
    el.addEventListener("ended", onEnd);
    return () => {
      el.removeEventListener("loadedmetadata", onMeta);
      el.removeEventListener("timeupdate", onTime);
      el.removeEventListener("ended", onEnd);
    };
  }, [audioUrl]);

  function toggle() {
    const el = ref.current;
    if (!el) return;
    if (playing) {
      el.pause();
      setPlaying(false);
    } else {
      void el.play().then(() => setPlaying(true));
    }
  }

  function onSeek(pct: number) {
    const el = ref.current;
    if (!el || !dur) return;
    el.currentTime = Math.max(0, Math.min(dur, pct * dur));
    setCur(el.currentTime);
    setSeekPct((el.currentTime / dur) * 100);
  }

  const pct = dur ? (cur / dur) * 100 : seekPct;

  return (
    <div className="rounded-[var(--radius-lg)] border border-[var(--color-border-default)] bg-[var(--color-bg-secondary)] p-6 shadow-[var(--shadow-card)]">
      <h3 className="text-lg font-semibold text-[var(--color-text-primary)]">Audio summary</h3>
      <p className="mt-1 text-xs text-[var(--color-text-muted)]">
        {audioProvider === "gemini"
          ? "Generated by Gemini TTS (fallback) · Based on your uploaded content"
          : audioProvider === "elevenlabs"
            ? "Generated by ElevenLabs · Based on your uploaded content"
            : "Based on your uploaded content"}
        {audioProvider === "gemini" ? (
          <span className="ml-2 text-[var(--color-accent-cyan)]">· via Gemini</span>
        ) : null}
      </p>

      <audio ref={ref} src={audioUrl} preload="metadata" className="hidden">
        <track kind="captions" />
      </audio>

      <div className="mt-6 flex flex-wrap items-center gap-4">
        <button
          type="button"
          onClick={() => toggle()}
          className="flex h-12 w-12 min-h-[48px] min-w-[48px] shrink-0 items-center justify-center rounded-full bg-[var(--color-accent-cyan)] text-[#0d1117] shadow-[var(--shadow-neon-cyan)] transition hover:brightness-110"
          aria-label={playing ? "Pause" : "Play"}
        >
          {playing ? (
            <span className="text-sm font-bold" aria-hidden>
              ❚❚
            </span>
          ) : (
            <span className="ml-0.5 text-lg" aria-hidden>
              ▶
            </span>
          )}
        </button>
        <div className="min-w-0 flex-1 space-y-2">
          <div
            role="slider"
            tabIndex={0}
            aria-valuenow={Math.round(pct)}
            aria-valuemin={0}
            aria-valuemax={100}
            aria-label="Playback position"
            className="cursor-pointer py-2"
            onClick={(e) => {
              const row = e.currentTarget.querySelector("[data-progress-hit]");
              if (!row) return;
              const rr = row.getBoundingClientRect();
              onSeek((e.clientX - rr.left) / rr.width);
            }}
            onKeyDown={(e) => {
              if (e.key === "ArrowRight") onSeek((cur + 5) / (dur || 1));
              if (e.key === "ArrowLeft") onSeek((cur - 5) / (dur || 1));
            }}
          >
            <div data-progress-hit>
              <ProgressBar value={pct} />
            </div>
          </div>
          <div className="flex justify-between font-mono text-xs text-[var(--color-text-muted)]">
            <span>{fmt(cur)}</span>
            <span>{fmt(dur)}</span>
          </div>
        </div>
        <a
          href={audioUrl}
          download
          className="inline-flex min-h-[44px] min-w-[44px] items-center justify-center gap-2 rounded-[var(--radius-md)] px-3 font-medium text-[var(--color-text-primary)] transition-colors hover:bg-[var(--color-bg-tertiary)] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--color-accent-cyan)]"
          aria-label="Download audio"
        >
          <svg width="18" height="18" viewBox="0 0 24 24" fill="none" aria-hidden>
            <path
              d="M12 4v12m0 0l4-4m-4 4L8 12M4 18h16"
              stroke="currentColor"
              strokeWidth="1.75"
              strokeLinecap="round"
            />
          </svg>
          <span className="hidden sm:inline">Download</span>
        </a>
      </div>

      <button
        type="button"
        onClick={() => setOpen((o) => !o)}
        className="mt-4 min-h-[44px] text-sm font-medium text-[var(--color-accent-cyan)] hover:underline"
      >
        {open ? "Hide transcript" : "Show transcript"}
      </button>
      {open && <p className="mt-2 whitespace-pre-wrap text-sm text-[var(--color-text-secondary)]">{transcript}</p>}
    </div>
  );
}
