"use client";

import { useEffect, useRef, useState } from "react";

function fmt(t: number) {
  if (!Number.isFinite(t)) return "0:00";
  const m = Math.floor(t / 60);
  const s = Math.floor(t % 60);
  return `${m}:${s.toString().padStart(2, "0")}`;
}

export function AudioPlayer({ audioUrl, transcript }: { audioUrl: string; transcript: string }) {
  const ref = useRef<HTMLAudioElement | null>(null);
  const [playing, setPlaying] = useState(false);
  const [dur, setDur] = useState(0);
  const [cur, setCur] = useState(0);
  const [open, setOpen] = useState(false);

  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    const onMeta = () => setDur(el.duration || 0);
    const onTime = () => setCur(el.currentTime || 0);
    const onEnd = () => setPlaying(false);
    el.addEventListener("loadedmetadata", onMeta);
    el.addEventListener("timeupdate", onTime);
    el.addEventListener("ended", onEnd);
    return () => {
      el.removeEventListener("loadedmetadata", onMeta);
      el.removeEventListener("timeupdate", onTime);
      el.removeEventListener("ended", onEnd);
    };
  }, [audioUrl]);

  function toggle() {
    const el = ref.current;
    if (!el) return;
    if (playing) {
      el.pause();
      setPlaying(false);
    } else {
      void el.play().then(() => setPlaying(true));
    }
  }

  function onSeek(pct: number) {
    const el = ref.current;
    if (!el || !dur) return;
    el.currentTime = Math.max(0, Math.min(dur, pct * dur));
    setCur(el.currentTime);
  }

  return (
    <div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-6">
      <h3 className="text-lg font-semibold text-white">Audio summary</h3>
      <p className="mt-1 text-xs text-slate-500">Generated by ElevenLabs · Based on your uploaded content</p>

      <audio ref={ref} src={audioUrl} preload="metadata" className="hidden">
        <track kind="captions" />
      </audio>

      <div className="mt-4 flex flex-wrap items-center gap-4">
        <button
          type="button"
          onClick={() => toggle()}
          className="flex h-12 w-12 items-center justify-center rounded-full bg-indigo-500 text-white hover:bg-indigo-400"
          aria-label={playing ? "Pause" : "Play"}
        >
          {playing ? "❚❚" : "▶"}
        </button>
        <div className="min-w-0 flex-1">
          <div
            role="slider"
            tabIndex={0}
            aria-valuenow={Math.round((cur / (dur || 1)) * 100)}
            className="h-2 cursor-pointer rounded-full bg-slate-800"
            onClick={(e) => {
              const r = e.currentTarget.getBoundingClientRect();
              onSeek((e.clientX - r.left) / r.width);
            }}
            onKeyDown={(e) => {
              if (e.key === "ArrowRight") onSeek((cur + 5) / (dur || 1));
              if (e.key === "ArrowLeft") onSeek((cur - 5) / (dur || 1));
            }}
          >
            <div
              className="h-2 rounded-full bg-indigo-400"
              style={{ width: `${dur ? (cur / dur) * 100 : 0}%` }}
            />
          </div>
          <div className="mt-1 flex justify-between font-mono text-xs text-slate-400">
            <span>{fmt(cur)}</span>
            <span>{fmt(dur)}</span>
          </div>
        </div>
        <a
          href={audioUrl}
          download
          className="rounded-lg border border-slate-600 px-4 py-2 text-sm font-semibold text-slate-100 hover:bg-slate-800"
        >
          Download
        </a>
      </div>

      <button
        type="button"
        onClick={() => setOpen((o) => !o)}
        className="mt-4 text-sm font-medium text-indigo-300 hover:text-indigo-200"
      >
        {open ? "Hide transcript" : "Show transcript"}
      </button>
      {open && <p className="mt-2 whitespace-pre-wrap text-sm text-slate-300">{transcript}</p>}
    </div>
  );
}
